in:
  type: file
  path_prefix: /home/shirz/home/shirz/Desktop/Final files for Descriptive/company_Languages_repos/csv/company_Languages_repos.csv
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: company, type: string}
    - {name: language, type: string}
    - {name: Repositories_count, type: long}
out:
  type: elasticsearch
  index: companies_languages_repos
  index_type: embulk
  nodes:
  - {host: localhost}
